POST http://localhost:12090/static
Content-Type: application/json

{}

// 7d18ef127cf829e266386654192ca91b

###
GET http://localhost:12090/static?name=dyp
Accept: application/json
Connection: close

###
GET http://localhost:12090/user
Accept: application/json
Connection: close

###
GET http://localhost:12090/api/item?id=99
Accept: application/json

###

GET http://localhost:12091/static
Accept: application/json


